### ISSUE TITLE
Fails to build with Manjaro Linux 24.0.6

### ISSUE THREAD

**Issue by rofaccess** [ankane/or-tools-ruby#63]
When installing this gem into a Manjaro Linux, I get an ERROR: Failed to build gem native extension.
## Specs
- Command: `gem install or-tools`
- Ruby: `ruby 3.3.4 (2024-07-09 revision be1089c8ec) [x86_64-linux]`
- OR Tools: `v0.12.0`
- OS: `Manjaro Linux 24.0.6`
## Specific Error
```
/home/dev/.rvm/gems/ruby-3.3.4@guard/gems/or-tools-0.12.0/ext/or-tools/vendor.rb:58:in `<top (required)>': Binary installation not available for this platform: manjaro  x86_64 (RuntimeError)
```
## Full Error
```
> gem install or-tools
Building native extensions. This could take a while...
ERROR:  Error installing or-tools:
        ERROR: Failed to build gem native extension.

    current directory: /home/dev/.rvm/gems/ruby-3.3.4@guard/gems/or-tools-0.12.0/ext/or-tools
/home/dev/.rvm/rubies/ruby-3.3.4/bin/ruby extconf.rb
checking for rice/rice.hpp in /home/dev/.rvm/gems/ruby-3.3.4@guard/gems/rice-4.3.1/include... yes
checking for -lstdc++fs... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include=${opt-dir}/include
        --without-opt-include
        --with-opt-lib=${opt-dir}/lib
        --without-opt-lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/rodrigo/.rvm/rubies/ruby-3.3.4/bin/$(RUBY_BASE_NAME)
        --with-stdc++fs-dir
        --without-stdc++fs-dir
        --with-stdc++fs-include=${stdc++fs-dir}/include
        --without-stdc++fs-include
        --with-stdc++fs-lib=${stdc++fs-dir}/lib
        --without-stdc++fs-lib
        --with-stdc++fslib
        --without-stdc++fslib
        --with-or-tools-dir
        --without-or-tools-dir
        --with-or-tools-include=${or-tools-dir}/include
        --without-or-tools-include
        --with-or-tools-lib=${or-tools-dir}/lib
        --without-or-tools-lib
/home/dev/.rvm/gems/ruby-3.3.4@guard/gems/or-tools-0.12.0/ext/or-tools/vendor.rb:58:in `<top (required)>': Binary installation not available for this platform: manjaro  x86_64 (RuntimeError)

Build the OR-Tools C++ library from source, then run:
bundle config build.or-tools --with-or-tools-dir=/path/to/or-tools

        from extconf.rb:15:in `require_relative'
        from extconf.rb:15:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/dev/.rvm/gems/ruby-3.3.4@guard/extensions/x86_64-linux/3.3.0/or-tools-0.12.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/dev/.rvm/gems/ruby-3.3.4@guard/gems/or-tools-0.12.0 for inspection.
Results logged to /home/dev/.rvm/gems/ruby-3.3.4@guard/extensions/x86_64-linux/3.3.0/or-tools-0.12.0/gem_make.out
```

**Comment by ankane** [comment]
Hi @rofaccess, see the error message:

```text
Build the OR-Tools C++ library from source, then run:
bundle config build.or-tools --with-or-tools-dir=/path/to/or-tools
```

**Comment by rofaccess** [comment]
Hello @ankane 
I made a pull request to add support for Manjaro Linux.
I have tested the installation and use of the gem into my local project, and, it seems to work correctly. Tests also pass.

Sorry if I made a mistake in the contribution process, this is my first pull request to collaborate with a project.
